Atlas.HlaMetadataDictionary.Test/IntegrationTests/Tests/SearchRelatedMetadataServiceTests.cs
Atlas.MultipleAlleleCodeDictionary.Test.Integration/Repositories/LargeMacDictionary.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/629)

fix: #628: Correct setup of MAC-related HMD integration test.

---

Atlas.Client.Models/CHANGELOG_Client.md
Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
Atlas.MatchPrediction/Atlas.MatchPrediction.csproj
Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj
Atlas.MatchingAlgorithm/Atlas.MatchingAlgorithm.csproj
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/639)

Versioning chores

---

ArchitecturalDecisionRecord/Phase2/005-Versioning.md
README_Deployment.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/642)

docs: #640: Add ADR relating to Atlas versioning scheme

---

Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorUpsertTests.cs
Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DonorValidationTests.cs
Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs
Atlas.DonorImport/Models/FileSchema/ImportDonorChangeType.cs
Atlas.DonorImport/Services/DonorFileImporter.cs
Atlas.DonorImport/Services/DonorRecordChangeApplier.cs
Atlas.DonorImport/Validators/SearchableDonorValidator.cs
README_DonorImport.md
README_Integration.md
Schemas/DonorUpdateFileSchema.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/654)

653 donors import upsert

---

build-pipeline.yml
test-pipeline.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/655)

chore: #653: Switch to ubuntu-latest image in build and test scripts

---

Atlas.Client.Models/Search/Results/Matching/PerLocus/Dpb1MismatchDirection.cs
Atlas.MatchingAlgorithm.Common/Models/SearchResults/LocusScoreDetails.cs
Atlas.MatchingAlgorithm.Test/Services/Search/Scoring/Aggregation/LocusAggregateMatchCategoryConverterTests.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/Aggregation/LocusMatchCategoryAggregator.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/DonorScoringService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/659)

Added Dpb1MismatchDirection to the LocusScoreDetails

---

Atlas.MatchingAlgorithm/Services/Search/Scoring/Aggregation/LocusMatchCategoryAggregator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/660)

Removed 'or pattern' from switch statement

---

Atlas.Client.Models/Search/Results/Matching/PerLocus/LocusSearchResult.cs
Atlas.MatchingAlgorithm/Services/Search/SearchService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/662)

Return value in LocusSearchResult

---

Atlas.Client.Models/CHANGELOG_Client.md
Atlas.Client.Models/Search/Results/MatchPrediction/HaplotypeFrequencySet.cs
Atlas.Client.Models/Search/Results/MatchPrediction/HlaFrequencySet.cs
Atlas.Client.Models/Search/Results/MatchPrediction/MatchProbabilityResponse.cs
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
Atlas.MatchPrediction.Test/Atlas.MatchPrediction.Test.csproj
Atlas.MatchPrediction.Test/Services/MatchProbability/MatchProbabilityServiceTests.cs
Atlas.MatchPrediction/ExternalInterface/Models/HaplotypeFrequencySet/HaplotypeFrequencySet.cs
Atlas.MatchPrediction/Services/HaplotypeFrequencies/HaplotypeFrequencyService.cs
Atlas.MatchPrediction/Services/MatchProbability/MatchProbabilityService.cs

Added internal Id, EthnicityCode, RegistryCode and populationId to the search result and moved nomenclature (kept original as well for backwards compatibility)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/661)

Return HF set information

---

Atlas.Client.Models/CHANGELOG_Client.md
Atlas.Client.Models/Search/Results/Matching/PerLocus/LocusSearchResult.cs
Atlas.Client.Models/Search/Results/Matching/PerLocus/MismatchDirection.cs
Atlas.MatchingAlgorithm.Common/Models/SearchResults/LocusScoreDetails.cs
Atlas.MatchingAlgorithm.Test/Services/Search/Scoring/Aggregation/LocusAggregateMatchCategoryConverterTests.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/Aggregation/LocusMatchCategoryAggregator.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/DonorScoringService.cs
Atlas.MatchingAlgorithm/Services/Search/SearchService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/663)

Renamed Dpb1MismatchDirection to MismatchDirection

---

terraform/core/outputs.tf
terraform/core/variables.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/665)

feature: #664: Expose Public API key and baseUrl to terraform outputs

---

terraform/core/outputs.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/666)

chore: #664: fix terraform script

---

README.md
README_Contribution_Versioning.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/669)

docs: NOVA-NONE: Add verioning + contribution doc

---

Atlas.DonorImport.Test/Services/DonorImportFileParserTests.cs
Atlas.DonorImport/Services/DonorImportFileParser.cs
Atlas.DonorImport/Services/DonorRecordChangeApplier.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/671)

feature: #670: Support donors Upsert change type within Full donor import process

---

terraform/core/outputs.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/673)

feature: #672: Expose Service Bus and Blob Storage resources connection details in terraform outputs

---

Atlas.Functions/Startup.cs
Atlas.MultipleAlleleCodeDictionary.Test/UnitTests/MacImporterTests.cs
Atlas.MultipleAlleleCodeDictionary/ExternalInterface/MacImporter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/701)

700-mac-import-errors

---

README_Support.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/702)

689 runbook

---

Atlas.DonorImport.Functions/Startup.cs
Atlas.DonorImport.Functions/local.settings.template.json
Atlas.DonorImport.Test.Integration/DependencyInjection/ServiceConfiguration.cs
Atlas.DonorImport.Test/Services/DonorRecordChangeApplierTests.cs
Atlas.DonorImport/ExternalInterface/DependencyInjection/ServiceConfiguration.cs
Atlas.DonorImport/ExternalInterface/Settings/NotificationConfigurationSettings.cs
Atlas.DonorImport/Services/DonorFileImporter.cs
Atlas.DonorImport/Services/DonorRecordChangeApplier.cs
terraform/core/modules/donor_import/function.tf
terraform/core/modules/donor_import/variables_release.tf
terraform/core/variables.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/706)

feature: #705: Allow disabling of donor import notifications

---

Atlas.Client.Models/Search/Results/Matching/MatchingResultsNotification.cs
Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs
Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/704)

691 failure details

---

Atlas.Client.Models/Atlas.Client.Models.csproj
Atlas.Client.Models/CHANGELOG_Client.md
Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
Atlas.MatchingAlgorithm.Client.Models/Scoring/IdentifiedDonorHla.cs
Atlas.MatchingAlgorithm.Client.Models/Scoring/ScoringRequest.cs
Atlas.MatchingAlgorithm.Client.Models/Scoring/ScoringResult.cs
Atlas.MatchingAlgorithm.Functions/Functions/ScoringFunctions.cs
Atlas.MatchingAlgorithm.Test/Services/Search/Scoring/MatchScoringServiceTests.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/DonorScoringService.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/MatchScoringService.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/ScoringRequestService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/712)

710 bulk score

---

ArchitecturalDecisionRecord/Phase2/007-MatchingAlgorithm_MismatchSearchSplit.md
Atlas.MatchingAlgorithm.Test/Services/Search/Matching/MatchCriteriaSimplifierTests.cs
Atlas.MatchingAlgorithm/Services/Search/Matching/MatchCriteriaSimplifier.cs
Atlas.MatchingAlgorithm/Services/Search/SearchService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/719)

709 mismatch breakdown

---

Atlas.MatchingAlgorithm.Data/Models/SearchResults/ScoreResult.cs
Atlas.MatchingAlgorithm/Mapping/ScoringResultProfile.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/731)

fix: Add mapping for new property to automapper config

---

Atlas.DonorImport.Data/CHANGELOG_Data.md
Atlas.MatchPrediction.Data/CHANGELOG_Data.md
Atlas.MatchingAlgorithm.Data.Persistent/CHANGELOG_Data.md
Atlas.MatchingAlgorithm.Data/CHANGELOG_Data.md
Atlas.RepeatSearch.Data/CHANGELOG_Data.md
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/789)

docs: Add data focus changelogs for each data project

---

Atlas.sln
README.md
README_MatchPredictionAlgorithm.md
README_MatchingAlgorithm.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/790)

docs: Add overview of match prediction algorithm

---

Atlas.DonorImport.Data/appsettings.json
Atlas.MatchPrediction.Data/appsettings.json
Atlas.MatchingAlgorithm.Data.Persistent/appsettings.json
Atlas.MatchingAlgorithm.Data/appsettings.json
Atlas.RepeatSearch.Data/appsettings.json

…error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/807)

fix: #806: Amend default connection string to resolve sql connection error

---

Atlas.MatchPrediction.Functions/Functions/MatchPredictionFunctions.cs
Atlas.MatchPrediction.Functions/host.json
Atlas.MatchPrediction.Functions/local.settings.template.json
Atlas.MatchPrediction.Test/Services/MatchPredictionRequestDispatcherTests.cs
Atlas.MatchPrediction.Test/Services/MatchPredictionRequestRunnerTests.cs
Atlas.MatchPrediction/ExternalInterface/BulkMessagePublisher.cs
Atlas.MatchPrediction/ExternalInterface/DependencyInjection/ServiceConfiguration.cs
Atlas.MatchPrediction/ExternalInterface/MatchPredictionRequestDispatcher.cs
Atlas.MatchPrediction/ExternalInterface/MatchPredictionRequestRunner.cs
Atlas.MatchPrediction/ExternalInterface/Models/MatchPredictionResultLocation.cs
Atlas.MatchPrediction/ExternalInterface/ResultsUpload/MatchPredictionRequestResultUploader.cs
Atlas.MatchPrediction/ExternalInterface/ResultsUpload/MatchProbabilityResultUploader.cs
Atlas.MatchPrediction/ExternalInterface/Settings/MatchPredictionRequestsSettings.cs
terraform/core/modules/match_prediction/function.tf
terraform/core/modules/match_prediction/servicebus.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/812)

chore: #805: Bulk publish match prediction result locations.

---

Atlas.DonorImport.Functions/host.json
Atlas.Functions.PublicApi/host.json
Atlas.Functions/host.json
Atlas.MatchPrediction.Functions/host.json
Atlas.MatchingAlgorithm.Functions.DonorManagement/host.json
Atlas.MatchingAlgorithm.Functions/host.json
Atlas.RepeatSearch.Functions/host.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/824)

chore: #818: Exclude custom events from Application Insights sampling

---

Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
terraform/core/modules/donor_import/servicebus.tf
terraform/core/modules/match_prediction/servicebus.tf
terraform/core/modules/matching_algorithm/servicebus.tf
terraform/core/modules/repeat_search/servicebus.tf
terraform/core/modules/support/servicebus.tf
terraform/core/servicebus.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/832)

chore: #831: Reduce TTL for audit service bus subscriptions.

---

.github/ISSUE_TEMPLATE/enhancement_request.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/838)

chore: New enhancement request issue template.

---

Atlas.sln
MiscTestingAndDebuggingResources/README_TestAndDebug.md
README.md
README_ArchitecturalOverview.md
README_Contribution_Versioning.md
README_DevelopmentSettings.md
README_DevelopmentStartUpGuide.md
README_ManualTesting.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/840)

docs: Clean-up of existing READMEs.

---

Atlas.sln
README_Deployment.md
terraform/core/variables.tf
terraform/system-tests/variables.tf

Please check these changes to the deployment readme are correct and clear. Thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/844)

docs: Clarifications made to the deployment readme.

---

README_Configuration.md
README_Deployment.md
README_Integration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/anthony-nolan/atlas/857)

docs: Minor updates to READMEs.

---

ArchitecturalDecisionRecord/Phase2/008-Publish_NuGet_Packages.md
Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj
Atlas.MatchingAlgorithm.Client.Models/CHANGELOG_MatchingAlgorithmClient.md
README_Contribution_Versioning.md
build-pipeline.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/863)

chore: #649: Publish Matching algorithm client models as NuGet package.

---

Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
README_DonorImport.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/867)

docs: #859: Add info on donor import validation.

---

Atlas.DonorImport.Test/TestHelpers/Builders/HlaBuilder.cs
Atlas.DonorImport.Test/Validators/OptionalImportedLocusValidatorTests.cs
Atlas.DonorImport.Test/Validators/OptionalTwoFieldStringValidatorTests.cs
Atlas.DonorImport.Test/Validators/RequiredImportedLocusValidatorTests.cs
Atlas.DonorImport.Test/Validators/RequiredTwoFieldStringValidatorTests.cs
Atlas.DonorImport/Validators/SearchableDonorValidator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/868)

chore: #859: Add locus name to donor import validation errors.

---

Atlas.Client.Models/CHANGELOG_Client.md
Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs
Atlas.MatchingAlgorithm.Test/Models/SearchResults/DenominatorTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/886)

feature: #885: Add matching and scoring denominators to result set.

---

Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs
Atlas.MatchingAlgorithm.Test/Services/Search/MatchingFailureNotificationSenderTests.cs
Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs
Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs
Atlas.MatchingAlgorithm/Services/Search/MatchingFailureNotificationSender.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/899)

#895: All non-completed searches should be in 1 place

---

Atlas.Functions.PublicApi/CHANGELOG_Atlas.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/911)

docs: Update Atlas product changelog.

---

Atlas.DonorImport.Test.Integration/DependencyInjection/ServiceConfiguration.cs
Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorAdditionTests.cs
Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs
Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs
Atlas.DonorImport.Test/Services/DonorUpdateCategoriserTests.cs
Atlas.DonorImport.Test/Validators/SearchableDonorValidatorTests.cs
Atlas.DonorImport/Services/DonorFileImporter.cs
Atlas.DonorImport/Services/DonorUpdateCategoriser.cs
Atlas.DonorImport/Validators/SearchableDonorValidator.cs
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
README_DonorImport.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/926)

#905 Update to a missing donor prevents processing of other records in import file

---

Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs
Atlas.DonorImport.FileSchema.Models/DonorChecker/DonorCheckerResults.cs
Atlas.DonorImport.FileSchema.Models/DonorChecker/DonorIdCheckerRequest.cs
Atlas.DonorImport.FileSchema.Models/DonorChecker/DonorIdCheckerResults.cs
Atlas.DonorImport.FileSchema.Models/DonorChecker/IDonorCheckerResults.cs
Atlas.DonorImport.Functions/Functions/DonorCheckerFunctions.cs
Atlas.DonorImport.Test/Services/DonorChecker/DonorIdCheckerFileParserTests.cs
Atlas.DonorImport.Test/Services/DonorChecker/DonorIdCheckerTests.cs
Atlas.DonorImport.Test/TestHelpers/Builders/DonorIdCheck/DonorIdCheckFileContentsBuilder.cs
Atlas.DonorImport.Test/TestHelpers/Models/DonorIdCheck/SerializableDonorIdCheckerFileContent.cs
Atlas.DonorImport/ExternalInterface/DependencyInjection/ServiceConfiguration.cs
Atlas.DonorImport/ExternalInterface/DonorReader.cs
Atlas.DonorImport/Services/DonorChecker/DonorCheckerBlobStorageClient.cs
Atlas.DonorImport/Services/DonorChecker/DonorIdChecker.cs
Atlas.DonorImport/Services/DonorChecker/DonorIdCheckerFileParser.cs
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
README_DonorImport.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/940)

#919 Report symmetric difference between WMDA donpool/donor type donor id set and Atlas set

---

Atlas.DonorImport.Test/Services/DonorChecker/DonorIdCheckerFileParserTests.cs
Atlas.DonorImport.Test/TestHelpers/Builders/DonorIdCheck/DonorIdCheckFileContentsBuilder.cs
Atlas.DonorImport.Test/TestHelpers/Models/DonorIdCheck/SerializableDonorIdCheckerFileContent.cs
Atlas.DonorImport/Services/DonorChecker/DonorIdCheckerFileParser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/949)

fix: #919: not throw exception for unexpected json property

---

Atlas.Client.Models/CHANGELOG_Client.md
Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
Atlas.Functions/Services/ResultsCombiner.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs
Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/965)

#953 add matching start time

---

Atlas.Client.Models/Search/Results/Matching/PerLocus/LocusPositionScoreDetails.cs
Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/Features/Scoring/IsAntigenMatch.feature
Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/Features/Scoring/IsAntigenMatch.feature.cs
Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/Features/Scoring/MatchConfidences.feature.cs
Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/Features/Scoring/MatchGrades.feature.cs
Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/StepDefinitions/ScoringSteps.cs
Atlas.MatchingAlgorithm.Test/Services/Search/Scoring/AntigenMatchCalculatorTests.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/AntigenMatching/AntigenMatchCalculator.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/AntigenMatching/AntigenMatchingService.cs
Atlas.MatchingAlgorithm/Services/Search/Scoring/DonorScoringService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/979)

fix: #978: No longer using match grade to calculate IsAntigenMatch.

---

Atlas.MatchPrediction.Test/Services/MatchProbability/MatchProbabilityServiceTests.cs
Atlas.MatchPrediction/Models/GenotypeAtDesiredResolutions.cs
Atlas.MatchPrediction/Services/MatchProbability/GenotypeConverter.cs
Atlas.MatchPrediction/Services/MatchProbability/MatchProbabilityService.cs

early PR that just contains a cosmetic refactor ahead of bug fix next week
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/983)

refactor: #982: Clean up MatchProbabilityService.

---

Atlas.DonorImport/ExternalInterface/DependencyInjection/ServiceConfiguration.cs
Atlas.DonorImport/Logger/DonorImportLogger.cs
Atlas.DonorImport/Logger/DonorImportLoggingContext.cs
Atlas.DonorImport/Services/DonorFileImporter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/985)

feature: #984: Tag all donor import logs with File name

---

Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorAdditionTests.cs
Atlas.DonorImport.Test.Integration/IntegrationTests/Import/DifferentialUpdates/DifferentialDonorEditTests.cs
Atlas.DonorImport.Test.Integration/IntegrationTests/Import/UploadOrderTests.cs
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/989)

984 tag all donor import logs with file name

---

Atlas.Common/ApplicationInsights/FileErrorEventModel.cs
Atlas.Common/ApplicationInsights/UploadErrorEventModel.cs
Atlas.MatchPrediction/Services/HaplotypeFrequencies/HaplotypeFrequencyService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/992)

fix: #990: Add HF set file name to import failure custom event

---

Atlas.Client.Models/Search/Results/MatchPrediction/MatchProbabilityPerLocusResponse.cs
Atlas.Functions.Test/Atlas.Functions.Test.csproj
Atlas.Functions.Test/Builders/LocusScoreResultBuilder.cs
Atlas.Functions.Test/Builders/ScoringResultBuilder.cs
Atlas.Functions.Test/Services/PositionalMatchCategoryOrientatorTests.cs
Atlas.Functions.Test/Services/PositionalMatchCategoryServiceTests.cs
Atlas.Functions/Atlas.Functions.csproj
Atlas.Functions/Services/MatchCategories/PositionalMatchCategoryOrientator.cs
Atlas.Functions/Services/MatchCategories/PositionalMatchCategoryService.cs
Atlas.Functions/Services/ResultsCombiner.cs
Atlas.Functions/Startup.cs
Atlas.sln
Atlas.sln.DotSettings
build-pipeline.yml

Use scoring result to re-orientate match prediction categories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1004)

996 mismatch orientation

---

Atlas.MatchPrediction.Data/Migrations/20230719134429_add-haplotype-frequency-set-active-index.Designer.cs
Atlas.MatchPrediction.Data/Migrations/20230719134429_add-haplotype-frequency-set-active-index.cs
Atlas.MatchPrediction.Data/Models/HaplotypeFrequencySet.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1019)

feature: #1017: Improve delete efficiency of inactive HF sets

---

README_Configuration.md
terraform/core/servicebus.tf
terraform/core/variables.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1025)

chore: Add ability to specify additional subscriptions for search-results-ready Service Bus topic

---

Atlas.Client.Models/CHANGELOG_Client.md
Atlas.Client.Models/Search/Results/LogFile/MatchingSearchLog.cs
Atlas.Client.Models/Search/Results/LogFile/SearchLog.cs
Atlas.Client.Models/Search/Results/SearchFailureInfo.cs
Atlas.Client.Models/Search/Results/SearchResultsNotification.cs
Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs
Atlas.Functions/Services/SearchCompletionMessageSender.cs
Atlas.ManualTesting/Services/SearchResultNotificationsPeeker.cs
Atlas.MatchingAlgorithm/Clients/ServiceBus/SearchServiceBusClient.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1036)

Improvements to search logging

---

Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1056)

feature: #1043: Catch and suppress HMD exception during Repeat Search

---

Atlas.RepeatSearch.Functions/Functions/RepeatSearchFunctions.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1057)

feature: #904: All failed repeat search requests should be in 1 place

---

Atlas.MatchPrediction.Functions/Functions/Debug/GenotypeImputationFunctions.cs
Atlas.MatchPrediction.Functions/Functions/Debug/MatchCalculationFunctions.cs
Atlas.MatchPrediction.Functions/Models/Debug/GenotypeImputationResponse.cs
Atlas.MatchPrediction.Functions/Models/Debug/GenotypeMatcherResponse.cs
Atlas.MatchPrediction.Test/TestHelpers/Builders/ImputedGenotypesBuilder.cs
Atlas.MatchPrediction/Models/ImputedGenotypes.cs
Atlas.MatchPrediction/Services/MatchProbability/ExpandedGenotypeTruncater.cs
Atlas.MatchPrediction/Services/MatchProbability/GenotypeMatcher.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1061)

chore: #1021: Calculate sum of likelihood during imputation.

---

Atlas.MatchingAlgorithm.Functions/Functions/Debug/HlaMetadataDictionaryFunctions.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1063)

1062 dpb1 debug

---

Atlas.MatchingAlgorithm.Test.Validation/ValidationTests/StepDefinitions/SpecificTestCases/SpecificTestDataSteps.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1075)

test: #1064: fix validation tests

---

terraform/core/modules/matching_algorithm/matching_algorithm_function.tf
terraform/core/modules/matching_algorithm/variables_di.tf
terraform/core/modules/repeat_search/function.tf
terraform/core/modules/repeat_search/variables_di.tf
terraform/system-tests/outputs.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1085)

chore: #1066: fix terraform setup for Azure app configuration

---

Atlas.MatchingAlgorithm.Data/CHANGELOG_Data.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1088)

docs: #1064: update changelog

---

Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1103)

fix: #1101: Set search request in repeat search result set.

---

Atlas.RepeatSearch/Services/Search/RepeatSearchDifferentialCalculator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1106)

fix: #1100: Repeat search failing at matching algorithm

---

README_Deployment.md
terraform/core/sql/createUsers/donorImport.sql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1111)

fix: #1110: Add db-writer permissions for matching user on Donors schema

---

Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1128)

chore: #1127: Do not replay repeat searches that fail validation.

---

ArchitecturalDecisionRecord/Phase2/009-Feature_Flags.md
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
README_Contribution_Versioning.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1130)

docs: Update changelog for v1.6.0

---

Atlas.MatchPrediction.Test.Integration/DependencyInjection/ServiceConfiguration.cs
Atlas.MatchPrediction.Test.Integration/IntegrationTests/MatchPrediction/IndividualSteps/PhenotypeExpansion/CompressedPhenotypeExpanderTestsBase.cs
Atlas.MatchPrediction.Test.Integration/IntegrationTests/MatchPrediction/IndividualSteps/PhenotypeExpansion/CompressedPhenotypeExpanderTestsWhereMatchingHlaVersionProvided.cs
Atlas.MatchPrediction.Test.Integration/IntegrationTests/MatchPrediction/IndividualSteps/PhenotypeExpansion/CompressedPhenotypeExpanderTestsWhereNoMatchingHlaVersionProvided.cs
Atlas.MatchPrediction.Test.Integration/IntegrationTests/MatchPrediction/MatchProbability/MatchProbabilityTestsBase.cs
Atlas.MatchPrediction.Test.Integration/TestHelpers/HaplotypeFrequencyImporter.cs
Atlas.MatchPrediction/Services/CompressedPhenotypeExpansion/CompressedPhenotypeExpander.cs
Atlas.MatchPrediction/Services/MatchProbability/GenotypeImputationService.cs
Atlas.sln.DotSettings

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1136)

chore: #1135: Only fetch HFs when subject is not high-res typed.

---

Atlas.MatchingAlgorithm.Data/Context/SearchAlgorithmContext.cs
Atlas.MatchingAlgorithm.Data/Migrations/20231218155540_AlterIndexOnDonorManagementLogTableIndexKeyIsOnlyLastUpdateDateTime.Designer.cs
Atlas.MatchingAlgorithm.Data/Migrations/20231218155540_AlterIndexOnDonorManagementLogTableIndexKeyIsOnlyLastUpdateDateTime.cs
Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorImportRepository.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1154)

chore #1116: Add recommended indexes to matching db

---

Atlas.Client.Models/Atlas.Client.Models.csproj
Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj
Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj
Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj
Atlas.Functions.PublicApi/CHANGELOG_Atlas.md
Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj
Atlas.MatchingAlgorithm.Data/CHANGELOG_Data.md
Atlas.MatchingAlgorithm.Data/Context/SearchAlgorithmContext.cs
Atlas.MatchingAlgorithm.Data/Migrations/20231218155540_AlterIndexOnDonorManagementLogTableIndexKeyIsOnlyLastUpdateDateTime.Designer.cs
Atlas.MatchingAlgorithm.Data/Migrations/20231218155540_AlterIndexOnDonorManagementLogTableIndexKeyIsOnlyLastUpdateDateTime.cs
Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorImportRepository.cs

@daria-sorokina-da need to release these index changes to UAT-WMDA-ATLAS ahead of data refresh running this weekend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1163)

Cherry pick #1116 for release in v1.6.1

---

Atlas.Debug.Client.Models/Atlas.Debug.Client.Models.csproj
Atlas.Debug.Client.Models/CHANGELOG_DebugClientModels.md
Atlas.Debug.Client.Models/DonorImport/DonorImportFileContents.cs
Atlas.Debug.Client.Models/DonorImport/DonorImportRequest.cs
Atlas.DonorImport.FileSchema.Models/DonorImportFileSchema.cs
Atlas.DonorImport.Functions/Functions/Debug/DonorImportFunctions.cs
Atlas.DonorImport/ExternalInterface/DependencyInjection/ServiceConfiguration.cs
Atlas.DonorImport/Services/Debug/DonorImportBlobStorageClient.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1185)

chore: #1179: New debug endpoint to post a donor import file.

---

Atlas.Debug.Client.Models/DonorImport/DonorDebugInfo.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1227)

chore: #1220: DebugDonorInfo now IEquatable.

---

Atlas.Common/ServiceBus/MessageReceiverFactory.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1232)

 Use ConcurrentDictionary in MessageReceiverFactory

---

Atlas.Debug.Client/Clients/DonorImportFunctionsClient.cs
Atlas.Debug.Client/Clients/MatchingAlgorithmFunctionsClient.cs
Atlas.MatchingAlgorithm.Functions/Functions/Debug/MatchingFunctions.cs
Atlas.MatchingAlgorithm.Functions/Startup.cs
Atlas.MatchingAlgorithm.Functions/local.settings.template.json
Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs
Atlas.MatchingAlgorithm/Services/Debug/MatchingResultNotificationsPeeker.cs
Atlas.MatchingAlgorithm/Settings/ServiceBus/MessagingServiceBusSettings.cs
terraform/core/modules/matching_algorithm/matching_algorithm_function.tf
terraform/core/modules/matching_algorithm/servicebus.tf
terraform/core/modules/matching_algorithm/variables.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1240)

chore: #1239: Added peek matching-results-ready endpoint.

---

Atlas.Common.Test/ServiceBus/BatchReceiving/ServiceBusMessageReceiverTests.cs
Atlas.Common/Debugging/ServiceBusPeeker.cs
Atlas.Common/ServiceBus/BatchReceiving/ServiceBusMessageReceiver.cs
Atlas.Common/ServiceBus/MessageReceiverFactory.cs
Atlas.Debug.Client/Clients/TopLevelFunctionsClient.cs
Atlas.DonorImport/ExternalInterface/DependencyInjection/ServiceConfiguration.cs
Atlas.DonorImport/Services/Debug/DonorImportResultsPeeker.cs
Atlas.Functions/Functions/Debug/SearchFunctions.cs
Atlas.Functions/Services/Debug/SearchResultNotificationsPeeker.cs
Atlas.Functions/Services/Debug/SupportMessagesPeeker.cs
Atlas.Functions/Settings/MessagingServiceBusSettings.cs
Atlas.Functions/Startup.cs
Atlas.Functions/local.settings.template.json
Atlas.ManualTesting/DependencyInjection/ServiceConfiguration.cs
Atlas.ManualTesting/Services/ServiceBus/DeadLetterReceiverFactory.cs
Atlas.ManualTesting/Services/ServiceBus/DeadLettersPeeker.cs
Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs
Atlas.MatchingAlgorithm/Services/Debug/MatchingResultNotificationsPeeker.cs
terraform/core/function.tf
terraform/core/servicebus.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1242)

Peek search notifications

---

Atlas.Common/AzureStorage/Blob/BlobDownloader.cs
Atlas.Common/Debugging/DebugLogger.cs
Atlas.Common/Debugging/DebugLoggerRegistration.cs
Atlas.Debug.Client.Models/SearchResults/DebugSearchResultsRequest.cs
Atlas.Debug.Client/Clients/MatchingAlgorithmFunctionsClient.cs
Atlas.MatchingAlgorithm.Functions/Functions/Debug/MatchingFunctions.cs
Atlas.MatchingAlgorithm.Functions/Startup.cs
Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs
Atlas.MatchingAlgorithm/Services/Debug/MatchingResultsDownloader.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1245)

chore: #1243: Debug endpoint added to fetch matching result set.

---

Atlas.Debug.Client/Atlas.Debug.Client.csproj
Atlas.Debug.Client/Clients/MatchingAlgorithmFunctionsClient.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1253)

chore: #1251: Add scoring endpoint to Debug client.

---

Atlas.MatchingAlgorithm.Test.Integration/IntegrationTests/DonorManagementServiceTests.cs
Atlas.MatchingAlgorithm/Services/DonorManagement/DonorManagementService.cs
Atlas.MatchingAlgorithm/Services/Donors/DonorService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1230)

fix: #1140: don't update DonorManagementLog if Donor wasn't updated

---

Atlas.Common/Debugging/DebugResultsDownloader.cs
Atlas.Debug.Client.Models/SearchResults/DebugSearchResultsRequest.cs
Atlas.Debug.Client.Models/Settings/RepeatSearchHttpFunctionSettings.cs
Atlas.Debug.Client/ClientConfiguration.cs
Atlas.Debug.Client/Clients/PublicApiFunctionsClient.cs
Atlas.Debug.Client/Clients/RepeatSearchFunctionsClient.cs
Atlas.Debug.Client/Clients/TopLevelFunctionsClient.cs
Atlas.Functions/Functions/Debug/RepeatSearchFunctions.cs
Atlas.Functions/Functions/Debug/SearchFunctions.cs
Atlas.Functions/Services/Debug/RepeatSearchResultNotificationsPeeker.cs
Atlas.Functions/Settings/MessagingServiceBusSettings.cs
Atlas.Functions/Startup.cs
Atlas.ManualTesting/DependencyInjection/ServiceConfiguration.cs
Atlas.ManualTesting/Functions/DebugClientFunctions.cs
Atlas.ManualTesting/local.settings.template.json
Atlas.MatchingAlgorithm.Functions/Functions/Debug/MatchingFunctions.cs
Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs
Atlas.RepeatSearch.Functions/Functions/Debug/RepeatSearchFunctions.cs
Atlas.RepeatSearch.Functions/Startup.cs
Atlas.RepeatSearch.Functions/local.settings.template.json
Atlas.RepeatSearch/ExternalInterface/DependencyInjection/ServiceConfiguration.cs
Atlas.RepeatSearch/Services/Debug/MatchingResultNotificationsPeeker.cs
Atlas.RepeatSearch/Settings/ServiceBus/MessagingServiceBusSettings.cs
Atlas.sln
terraform/core/function.tf
terraform/core/modules/repeat_search/function.tf
terraform/core/modules/repeat_search/outputs.tf
terraform/core/modules/repeat_search/servicebus.tf
terraform/core/modules/repeat_search/variables.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1256)

Repeat search debug endpoints

---

Atlas.DonorImport/Services/DonorFileImporter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1257)

fix: #1186: do not dead-letter after DuplicateDonorFileImportException

---

Atlas.MatchingAlgorithm.Functions/host.json
Atlas.MatchingAlgorithm/Services/Search/Matching/MatchingService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1273)

chore: #1268: fixed missprint

---

build-pipeline.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1293)

publish debug client separately to other Atlas packages

---

ArchitecturalDecisionRecord/Phase2/010-Publish_Debug_Client.md
Atlas.Debug.Client.Models/Atlas.Debug.Client.Models.csproj
Atlas.Debug.Client.Models/CHANGELOG_DebugClientModels.md
Atlas.Debug.Client/Atlas.Debug.Client.csproj
Atlas.Debug.Client/CHANGELOG_DebugClient.md
README_Contribution_Versioning.md
build-pipeline.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1296)

Simplify debug versioning

---

Atlas.Client.Models/Atlas.Client.Models.csproj
Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj
Atlas.Debug.Client/Atlas.Debug.Client.csproj
Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj
Atlas.DonorImport/Atlas.DonorImport.csproj
Atlas.ManualTesting/Atlas.ManualTesting.csproj
Atlas.MatchPrediction.Functions/Atlas.MatchPrediction.Functions.csproj
Atlas.MatchPrediction.Test.Verification/Atlas.MatchPrediction.Test.Verification.csproj
Atlas.MatchingAlgorithm.Api/Atlas.MatchingAlgorithm.Api.csproj
Atlas.MatchingAlgorithm.Functions.DonorManagement/Atlas.MatchingAlgorithm.Functions.DonorManagement.csproj
Atlas.MatchingAlgorithm.Functions/Atlas.MatchingAlgorithm.Functions.csproj
Atlas.MatchingAlgorithm.Test.Validation/Atlas.MatchingAlgorithm.Test.Validation.csproj
Atlas.MatchingAlgorithm/Atlas.MatchingAlgorithm.csproj
Atlas.RepeatSearch.Functions/Atlas.RepeatSearch.Functions.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1290)

chore: #1285: Update Newton.Json package to latest version

---

terraform/core/servicebus.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1297)

feature: CBT-1274: Update terraform for search tracking servicebus

---

Atlas.MatchPrediction.Functions/Functions/Debug/MatchCalculationFunctions.cs
Atlas.MatchPrediction.Functions/Services/Debug/GenotypeLikelihoodFormatter.cs
Atlas.MatchPrediction/Models/GenotypeMatchDetails.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1301)

1294 stream response

---

Search.Tracking/Atlas.SearchTracking.csproj
Search.Tracking/Clients/SearchTrackingServiceBusClient.cs
Search.Tracking/Enums/SearchTrackingEventType.cs
Search.Tracking/Settings/ServiceBus/MessagingServiceBusSettings.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1307)

feature: #1274: CBT-1473: Create client to send events to the topic

---

Atlas.SearchTracking.Data/Atlas.SearchTracking.Data.csproj
Atlas.sln

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1310)

feature: #1274: CBT-1472: Add project Atlas.SearchTracking.Data

---

Atlas.SearchTracking.Data.Test/Atlas.SearchTracking.Data.Test.csproj
Atlas.SearchTracking.Data.Test/Builders/MatchPredictionEntityBuilder.cs
Atlas.SearchTracking.Data.Test/Builders/MatchingAlgorithmAttemptBuilder.cs
Atlas.SearchTracking.Data.Test/Builders/SearchRequestEntityBuilder.cs
Atlas.SearchTracking.Data.Test/Repositories/MatchPredictionRepositoryTests.cs
Atlas.SearchTracking.Data.Test/Repositories/SearchRequestMatchingAlgorithmAttemptTimingRepositoryTests.cs
Atlas.SearchTracking.Data.Test/Repositories/SearchRequestRepositoryTests.cs
Atlas.SearchTracking.Data.Test/TestHelpers/SearchTrackingContextTestBase.cs
Atlas.SearchTracking.Data.Test/TestHelpers/SqliteMemoryContext.cs
Atlas.SearchTracking.Data/Atlas.SearchTracking.Data.csproj
Atlas.SearchTracking.Data/Repositories/MatchPredictionRepository.cs
Atlas.SearchTracking.Data/Repositories/SearchRequestMatchingAlgorithmAttemptTimingRepository.cs
Atlas.SearchTracking.Data/Repositories/SearchRequestRepository.cs
Atlas.sln

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1316)

feature: #1274: CBT-1472: Add unit tests for DAL

---

Atlas.Client.Models/Atlas.Client.Models.csproj
Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj
Atlas.Debug.Client.Models/Atlas.Debug.Client.Models.csproj
Atlas.Debug.Client/Atlas.Debug.Client.csproj
Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj
Atlas.DonorImport/ExternalInterface/Models/Donor.cs
Atlas.DonorImport/ExternalInterface/Models/SearchableDonorInformation.cs
Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj
Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj
Atlas.MatchingAlgorithm/Mapping/DonorImportMapping.cs
Atlas.MatchingAlgorithm/Services/DataRefresh/DonorImport/DonorImporter.cs
Atlas.MatchingAlgorithm/Services/DonorManagement/SearchableDonorUpdateConverter.cs

…efresh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1319)

feature #1318: use LastUpdated from persistend database during data refresh

---

test-pipeline.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1321)

chore: fixed tests pipeline

---

Atlas.DonorImport.Functions/host.json
Atlas.Functions.PublicApi/host.json
Atlas.Functions/host.json
Atlas.MatchPrediction.Functions/host.json
Atlas.MatchPrediction.Test.Validation/host.json
Atlas.MatchingAlgorithm.Functions.DonorManagement/host.json
Atlas.MatchingAlgorithm.Functions/host.json
Atlas.RepeatSearch.Functions/host.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1323)

fix: #1320: Fixed the sampling settings for all Atlas functions to not sample: Requests, Events, Traces and Exceptions

---

Atlas.DonorImport/Models/Mapping/DatabaseDonorMaps.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1324)

fix #1318: donor dto mapping fix

---

Atlas.MatchingAlgorithm/Services/DataRefresh/DataRefreshRequester.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1325)

fix #1318: set ShouldMarkAllDonorsAsUpdated always true

---

Atlas.DonorImport/Helpers/SearchableDonorUpdateMapper.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1329)

fix #1318: fixed DonorUpdateMapper

---

build-pipeline.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1330)

feature: CBT-2220: Add deployment of Search Tracking projects

---

Atlas.MatchingAlgorithm.Functions/Startup.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1331)

fix: #1274: CBT-1475: Fix broken build

---

Atlas.RepeatSearch.Test/Services/Search/RepeatSearchDispatcherTests.cs
Atlas.RepeatSearch.Test/TestHelpers/Builders/SearchRequestedEventBuilder.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1332)

fix: #1274: CBT-1475: fix unit test

---

Atlas.SearchTracking.Data/Context/ContextFactory.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1334)

fix: #1274: CBT-1475: rename search tracking connection string

---

Atlas.Functions.PublicApi/Startup.cs
Atlas.Functions.PublicApi/local.settings.template.json
Atlas.RepeatSearch/ExternalInterface/DependencyInjection/ProjectInterfaceOrchestrationConfiguration.cs
terraform/core/function.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1336)

Bug cbt 2324 add search tracking variables to terraform

---

Atlas.SearchTracking.Functions/Atlas.SearchTracking.Functions.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1339)

feature: CBT-1475: Amend build folder for search tracking function

---

terraform/core/outputs_ci.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1341)

feature: CBT-1475: Add search tracking username to terraform output file

---

Atlas.SearchTracking.Common/Clients/SearchTrackingServiceBusClient.cs
Atlas.SearchTracking.Common/Config/SearchTrackingConstants.cs
Atlas.SearchTracking.Functions/SearchTrackingFunctions.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1344)

feature: CBT-1475: Update search tracking message event type

---

Atlas.SearchTracking.Data/Context/ContextFactory.cs
Atlas.SearchTracking.Data/appsettings.json
Atlas.SearchTracking.Functions/Program.cs
Atlas.SearchTracking.Functions/local.settings.template.json
terraform/core/modules/search_tracking/function.tf
terraform/core/scripts/migrate_users.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1345)

fix: CBT-1475: Fix of the connection string for the Search Tracking function

---

Atlas.MatchingAlgorithm.Data/Repositories/DonorUpdates/DonorUpdateRepository.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1348)

fix: CBT-2555: Amend sql query when setting IsAvailableForSearch

---

Atlas.Functions/Startup.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1355)

fix: #1354 Add missing service bus registration

---

Atlas.MatchingAlgorithm.Test/Services/Search/MatchingAlgorithmSearchTrackingDispatcherTests.cs
Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs
Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs
Atlas.MatchingAlgorithm/Models/MatchingAlgorithmSearchTrackingContext.cs
Atlas.MatchingAlgorithm/Services/Search/MatchingAlgorithmSearchTrackingContextManager.cs
Atlas.MatchingAlgorithm/Services/Search/MatchingAlgorithmSearchTrackingDispatcher.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1353)

feature: CBT-1476: Send matching algorithm attempt started event

---

Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1356)

fix: NONE: Fix failing search runner unit tests

---

Atlas.MatchingAlgorithm.Functions/Functions/SearchFunctions.cs
Atlas.MatchingAlgorithm.Test/Services/Search/MatchingAlgorithmSearchTrackingDispatcherTests.cs
Atlas.MatchingAlgorithm/Services/Search/Matching/MatchingService.cs
Atlas.MatchingAlgorithm/Services/Search/MatchingAlgorithmSearchTrackingDispatcher.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1358)

feature: CBT-1476: Send Matching Algorithm core matching started event

---

Atlas.MatchingAlgorithm/Services/Search/Matching/MatchingService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1360)

feature: CBT-1476: Send matching algorithm core matching ended event

---

Atlas.MatchingAlgorithm.Data/Repositories/PGroupRepository.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs
Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1363)

feature: CBT-1476: Send matching algorithm persisting results events

---

Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1366)

feature: CBT-1476: Start handling validation exception in search

---

Atlas.Client.Models/Atlas.Client.Models.csproj
Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj
Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj
Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj
Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj
terraform/core/function.tf
terraform/core/modules/repeat_search/outputs.tf
terraform/core/outputs.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1369)

ops: CBT-1071: export repeat_search module in the Terraform outputs

---

Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs
Atlas.MatchingAlgorithm/Services/Search/MatchingAlgorithmSearchTrackingDispatcher.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs
Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1365)

feature: CBT-1476: Send matching algorithm completed event

---

Atlas.Functions.PublicApi/Startup.cs
Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs
Atlas.Functions/DurableFunctions/Search/Client/SearchClientFunctions.cs
Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs
Atlas.Functions/Services/MatchPredictionSearchTrackingDispatcher.cs
Atlas.Functions/Startup.cs
Atlas.Functions/local.settings.template.json
Atlas.MatchPrediction.Functions/Startup.cs
Atlas.MatchingAlgorithm.Api/Startup.cs
Atlas.MatchingAlgorithm.Functions/Startup.cs
Atlas.MatchingAlgorithm.Test.Integration/DependencyInjection/ServiceConfiguration.cs
Atlas.MatchingAlgorithm/DependencyInjection/ProjectInterfaceOrchestrationConfiguration.cs
Atlas.MatchingAlgorithm/DependencyInjection/ServiceConfiguration.cs
Atlas.RepeatSearch.Functions/Startup.cs
Atlas.RepeatSearch/ExternalInterface/DependencyInjection/ProjectInterfaceOrchestrationConfiguration.cs
Atlas.RepeatSearch/ExternalInterface/DependencyInjection/ServiceConfiguration.cs
Atlas.SearchTracking.Common/Clients/SearchTrackingServiceBusClient.cs
Atlas.SearchTracking.Common/Settings/ServiceBus/SearchTrackingServiceBusSettings.cs
Atlas.SearchTracking.Functions/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1370)

feature: CBT-1477: Send search tracking events for match prediction

---

Atlas.Functions/local.settings.template.json
Atlas.MatchPrediction.Test.Verification/local.settings.template.json
README_Integration.md
terraform/core/variables.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1375)

fix: ASRT-26103: Mac code url updates

---

Atlas.MatchingAlgorithm.Functions.DonorManagement/Atlas.MatchingAlgorithm.Functions.DonorManagement.csproj
Atlas.MatchingAlgorithm.Functions.DonorManagement/Functions/HealthCheckFunctions.cs
Atlas.MatchingAlgorithm.Functions.DonorManagement/Startup.cs
terraform/core/modules/matching_algorithm/donor_management_function.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1382)

feature: CBT-3345: Added Donor Management function health check

---

Atlas.MatchingAlgorithm/Clients/Scoring/MatchingAlgorithmScoringFunctionsClient.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1383)

fix: CBT-3343: Fix build

---

Atlas.SearchTracking.Functions/Functions/HealthCheckFunctions.cs
Atlas.SearchTracking.Functions/Functions/SearchTrackingFunctions.cs
Atlas.SearchTracking.Functions/Program.cs
terraform/core/modules/search_tracking/function.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1384)

feature: CBT-3345: Added Search Tracking health check function

---

Atlas.MatchingAlgorithm/Clients/Scoring/MatchingAlgorithmScoringFunctionsClient.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1385)

feature: CBT-2878: Fix url for matching funtion scoring client

---

Atlas.Client.Models/Atlas.Client.Models.csproj
Atlas.Common.Public.Models/Atlas.Common.Public.Models.csproj
Atlas.Debug.Client.Models/Atlas.Debug.Client.Models.csproj
Atlas.DonorImport.FileSchema.Models/Atlas.DonorImport.FileSchema.Models.csproj
Atlas.Functions.PublicApi/Atlas.Functions.PublicApi.csproj
Atlas.MatchingAlgorithm.Client.Models/Atlas.MatchingAlgorithm.Client.Models.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1391)

chore: Version bump to 2.5.0

---

Atlas.MatchPrediction.Functions/Functions/MatchPredictionFunctions.cs
Atlas.MatchPrediction/ExternalInterface/DependencyInjection/ServiceConfiguration.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1394)

Fix: CBT-3806 Resolve match prediction function dependency issue

---

Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs
Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs
Atlas.SearchTracking.Common/Models/MatchPredictionCompletedEvent.cs
Atlas.SearchTracking.Common/Models/MatchingAlgorithmCompletedEvent.cs
Atlas.SearchTracking.Data.Test/Builders/MatchingAlgorithmAttemptBuilder.cs
Atlas.SearchTracking.Data.Test/Builders/SearchRequestEntityBuilder.cs
Atlas.SearchTracking.Data.Test/Repositories/SearchRequestMatchingAlgorithmAttemptsRepositoryTests.cs
Atlas.SearchTracking.Data.Test/Repositories/SearchRequestRepositoryTests.cs
Atlas.SearchTracking.Data/Repositories/SearchRequestMatchingAlgorithmAttemptTimingRepository.cs
Atlas.SearchTracking.Data/Repositories/SearchRequestRepository.cs
Atlas.SearchTracking.Test/Services/SearchTrackingEventProcessorTests.cs

Fix: CBT-4102: Fixed matching algorithm processing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1397)

Fix: CBT-4102: Fixed matching algorithm processing

---

Atlas.Functions/DurableFunctions/Search/Activity/SearchActivityFunctions.cs
Atlas.Functions/DurableFunctions/Search/Orchestration/SearchOrchestrationFunctions.cs
Atlas.Functions/Services/MatchPredictionSearchTrackingDispatcher.cs
Atlas.MatchingAlgorithm.Test/Services/Search/MatchingAlgorithmSearchTrackingDispatcherTests.cs
Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs
Atlas.MatchingAlgorithm/Models/MatchingAlgorithmSearchTrackingContext.cs
Atlas.MatchingAlgorithm/Services/Search/MatchingAlgorithmSearchTrackingContextManager.cs
Atlas.MatchingAlgorithm/Services/Search/MatchingAlgorithmSearchTrackingDispatcher.cs
Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs
Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs
Atlas.SearchTracking.Common/Models/MatchingAlgorithmCompletedEvent.cs
Atlas.SearchTracking.Data.Test/Repositories/SearchRequestMatchingAlgorithmAttemptsRepositoryTests.cs
Atlas.SearchTracking.Data.Test/Repositories/SearchRequestRepositoryTests.cs
Atlas.SearchTracking.Data/Repositories/SearchRequestMatchingAlgorithmAttemptTimingRepository.cs
Atlas.SearchTracking.Data/Repositories/SearchRequestRepository.cs
Atlas.SearchTracking.Test/Services/SearchTrackingEventProcessorTests.cs

Fix: CBT-4106: Fixed sending wrong Search Request ID in Repeat Search
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1398)

Fix: CBT-4106: Fixed sending wrong Search Request ID in Repeat Search

---

Atlas.Functions.PublicApi/Startup.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1403)

bug: CBT-4171: Fix build failure

---

Atlas.MatchingAlgorithm.Functions.DonorManagement/Functions/DonorManagementFunctions.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1406)

bug: CBT-4024: Add parameter IsBatched to Donor Management functions

---

terraform/core/modules/search_tracking/function.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1408)

bug: CBT-4248: Assign the Search-Tracking-Function a scaling limit of 1

---

Atlas.SearchTracking.Functions/host.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1409)

bug: CBT-4266: Add retry for HandleSearchTrackingEvent function

---

Atlas.Functions.PublicApi/local.settings.template.json
Atlas.Functions/local.settings.template.json
Atlas.SearchTracking.Common/Settings/ServiceBus/SearchTrackingServiceBusSettings.cs
terraform/core/function.tf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1411)

bug: CBT-4293: Add SendRetry configuration to Functions

---

Atlas.SearchTracking.Functions/Functions/SearchTrackingEventFunctions.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1414)

bug: CBT-4266: Add delay for HandleSearchTrackingEvent function

---

Atlas.RepeatSearch/Clients/RepeatSearchServiceBusClient.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1423)

bug: MCT-95: Add custom properties to repeat search request messages
